spring.application.name=orderflow

spring.datasource.url=jdbc:postgresql://localhost:5432/OrderFlow
spring.datasource.username=postgres
spring.datasource.password=oderflow

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true